_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    BBOX_REG_LOSS_WEIGHT: 1.0
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_WEIGHT: 12.0

INPUT:
  MIN_SIZE_TRAIN:  (800, )
  MIN_SIZE_TEST: 800

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (12000, 16000)
  MAX_ITER: 18000  # 17.4 epochs
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 500
  EVAL_START_ITER: 15000
